"""Canonical audit action identifiers."""

from __future__ import annotations


class AuditAction:
    AUTH_LOGIN = "AUTH_LOGIN"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGOUT = "AUTH_LOGOUT"

    PROVISIONING_REQUEST_CREATED = "PROVISIONING_REQUEST_CREATED"
    DRY_RUN_PERFORMED = "DRY_RUN_PERFORMED"
    IP_CONFLICT_CHECK_PERFORMED = "IP_CONFLICT_CHECK_PERFORMED"

    JOB_STARTED = "JOB_STARTED"
    JOB_STAGE_SUCCEEDED = "JOB_STAGE_SUCCEEDED"
    JOB_STAGE_FAILED = "JOB_STAGE_FAILED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_PARTIALLY_COMPLETED = "JOB_PARTIALLY_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_STAGE_RETRIED = "JOB_STAGE_RETRIED"

    VM_CREATED = "VM_CREATED"
    NETWORK_MODIFIED = "NETWORK_MODIFIED"
    CERTIFICATE_INSTALLED = "CERTIFICATE_INSTALLED"
    APPLICATION_INSTALLED = "APPLICATION_INSTALLED"

    VCENTER_CREATED = "VCENTER_CREATED"
    VCENTER_UPDATED = "VCENTER_UPDATED"
    VCENTER_DELETED = "VCENTER_DELETED"
    VCENTER_TESTED = "VCENTER_TESTED"

    SITE_CREATED = "SITE_CREATED"
    SITE_UPDATED = "SITE_UPDATED"
    SITE_DELETED = "SITE_DELETED"

    CERTIFICATE_PACKAGE_CREATED = "CERTIFICATE_PACKAGE_CREATED"
    CERTIFICATE_PACKAGE_UPDATED = "CERTIFICATE_PACKAGE_UPDATED"
    CERTIFICATE_PACKAGE_DELETED = "CERTIFICATE_PACKAGE_DELETED"
    CERTIFICATE_CREATED = "CERTIFICATE_CREATED"
    CERTIFICATE_UPDATED = "CERTIFICATE_UPDATED"
    CERTIFICATE_DELETED = "CERTIFICATE_DELETED"

    APPLICATION_CREATED = "APPLICATION_CREATED"
    APPLICATION_UPDATED = "APPLICATION_UPDATED"
    APPLICATION_DELETED = "APPLICATION_DELETED"

    CREDENTIAL_CREATED = "CREDENTIAL_CREATED"
    CREDENTIAL_DELETED = "CREDENTIAL_DELETED"

    SETTINGS_UPDATED = "SETTINGS_UPDATED"
