"""API schema package — re-exports the most commonly used contracts."""

from app.schemas.auth import LoginRequest, TokenResponse, UserOut
from app.schemas.common import HealthComponent, HealthReport, Page, ReadinessReport
from app.schemas.dashboard import DashboardResponse, DashboardStats
from app.schemas.infrastructure import (
    ClusterOut,
    DatacenterOut,
    DatastoreClusterOut,
    DatastoreOut,
    HostOut,
    IsoImageOut,
    NetworkOut,
    ResourcePoolOut,
    TemplateOut,
    VCenterSummary,
)
from app.schemas.jobs import JobDetailOut, JobListResponse, JobOut, JobStepOut, RetryRequest
from app.schemas.logs import LogEventOut, LogListResponse, LogSeverity
from app.schemas.provisioning import (
    AdapterType,
    CheckStatus,
    DiskProvisioning,
    DiskSpec,
    FirmwareType,
    HardwareSpec,
    IpConflictCheckRequest,
    IpConflictReport,
    IpMode,
    Ipv4Config,
    NetworkSpec,
    PreflightCheck,
    PreflightReport,
    ProvisioningRequest,
    VmSpec,
)

__all__ = [
    "AdapterType",
    "CheckStatus",
    "ClusterOut",
    "DatacenterOut",
    "DatastoreClusterOut",
    "DatastoreOut",
    "DiskProvisioning",
    "DiskSpec",
    "FirmwareType",
    "HardwareSpec",
    "HealthComponent",
    "HealthReport",
    "HostOut",
    "IpConflictCheckRequest",
    "IpConflictReport",
    "IpMode",
    "IsoImageOut",
    "Ipv4Config",
    "JobDetailOut",
    "JobListResponse",
    "JobOut",
    "JobStepOut",
    "LoginRequest",
    "LogEventOut",
    "LogListResponse",
    "LogSeverity",
    "NetworkOut",
    "NetworkSpec",
    "Page",
    "PreflightCheck",
    "PreflightReport",
    "ProvisioningRequest",
    "ReadinessReport",
    "ResourcePoolOut",
    "RetryRequest",
    "TemplateOut",
    "TokenResponse",
    "UserOut",
    "VCenterSummary",
    "VmSpec",
    "DashboardResponse",
    "DashboardStats",
]
